module.exports = {
  apps: [
    {
      name: 'darital-api',
      script: './apps/api/dist/main.js',
      cwd: '/var/www/darital',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: '/var/www/darital/logs/api-error.log',
      out_file: '/var/www/darital/logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
    },
    {
      name: 'darital-admin',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: '/var/www/darital/apps/admin-web',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/var/www/darital/logs/admin-error.log',
      out_file: '/var/www/darital/logs/admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
    },
    {
      name: 'darital-tenant',
      script: 'node_modules/.bin/next',
      args: 'start -p 3002',
      cwd: '/var/www/darital/apps/tenant-web',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      error_file: '/var/www/darital/logs/tenant-error.log',
      out_file: '/var/www/darital/logs/tenant-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      watch: false,
    },
  ],
};

