UPDATE "users" SET "role" = 'WATER_COLLECTOR' WHERE "role" = 'WATER_OPERATOR';
UPDATE "users" SET "role" = 'ELECTRICITY_COLLECTOR' WHERE "role" = 'ELECTRICITY_OPERATOR';
UPDATE "users" SET "role" = 'GAS_COLLECTOR' WHERE "role" = 'GAS_OPERATOR';
